### ISSUE TITLE
Don't z into subdirectories

### ISSUE THREAD

**Issue by piegamesde** [agkozak/zsh-z#14]
Assume I have a directory structure like:

```
/foo
/foo/bar
/foo/baz
/foobar
```

`/foo` is my main folder from which I cd into `bar` and `baz` on a regular basis. When I run `z foo`, it will now jump me to `/foo/bar` since it is the folder I currently use the most. But I find this counter-intuitive and would prefer to land in `/foo`.

A solution to this is to only match the actual directory's name, ignoring all of the parent directories.

**Comment by agkozak** [comment]
You're right -- I think that *is* how it should work. I'll have a fix ready soon.

**Comment by agkozak** [comment]
Would you like to try out the changes I made on the `develop` branch? If what I've done works, I can merge them to `master`.

**Comment by piegamesde** [comment]
@agkozak Thank you for your work. Is there a way to know if I'm running the correct `z` version, because I (think I) switched to the `develop` branch and don't notice any difference. Does the change apply to existing database entries or shall I test this with previously unseen folders?

**Comment by agkozak** [comment]
Make sure, after running

    git checkout develop

to run

    git pull

That will bring you up to the latest version. If you run

    git log

You'll see that on Feb 11, I made a commit named

    1792063854f3122e49b8de67578dc4ddf6ad8ca7
    More desirable behavior from _zsh_find_common_root

That's the one you need.

**Comment by piegamesde** [comment]
Then it's not working. Don't know if related, when I run `source .oh-my-zsh/custom/plugins/zsh-z/zsh-z.plugin.zsh` I get `.oh-my-zsh/custom/plugins/zsh-z/zsh-z.plugin.zsh:173: parse error near '}'`

**Comment by agkozak** [comment]
That's very strange.

Let's make sure you're really using the latest version. You can copy and paste the following

    rm -rf "$HOME/.oh-my-zsh/custom/plugins/zsh-z"
    git clone https://github.com/agkozak/zsh-z "$HOME/.oh-my-zsh/custom/plugins/zsh-z"
    cd "$HOME/.oh-my-zsh/custom/plugins/zsh-z"
    git checkout develop
    zsh

Give it a try. If you're still having trouble, let me know what happens, and include the output of

    echo $ZSH_VERSION

and

    uname -a

Thanks so much for being patient and for helping to improve the plugin.

**Comment by piegamesde** [comment]
Still not working. Version is `5.7.1` and kernel is `Linux 5.5.2-arch1-1 #1 SMP PREEMPT Tue, 04 Feb 2020 18:56:18 +0000 x86_64 GNU/Linux`

**Comment by agkozak** [comment]
When you say it's not working, do you mean that the original problem has not been fixed, or that every time you load the shell you see

    .oh-my-zsh/custom/plugins/zsh-z/zsh-z.plugin.zsh:173: parse error near '}'

**Comment by piegamesde** [comment]
The original problem has not been fixed. I only get that error when I manually source the file as per the installation instructions (instead of loading it through oh-my-zsh)

**Comment by agkozak** [comment]
I'm not sure where to go from here. I'm also running `zsh` v5.7.1 on multiple machines, and I can load the plugin with a framework *and* source directly. I've even got it working with `oh-my-zsh` on one machine.

Just so we make absolutely sure that your script is intact -- can you open `zsh-z.plugin.zsh` and tell me what line 342 says?

**Comment by piegamesde** [comment]
`     [[ $x != $short* ]] && return`

**Comment by agkozak** [comment]
> [[ $x != $short* ]] && return

OK. That's exactly what it should be. I'll try to think what else could possibly be going wrong.

**Comment by agkozak** [comment]
Could you post your `.zshrc`? I just want to see if you're using any aliases or things like that that could be interacting with the code.

**Comment by piegamesde** [comment]
```sh
export ZSH=~/.oh-my-zsh
ZSH_THEME="af-magic"
DISABLE_AUTO_TITLE="true"
function precmd () {
  window_title="\033]0;${PWD##*/}\007"
  echo -ne "$window_title"
}
zstyle ':completion:*' menu select
export ZSHZ_NO_RESOLVE_SYMLINKS=1
plugins=(
  git
  gradle
  per-directory-history
  sudo
  systemd
  git zsh-z
)
source $ZSH/oh-my-zsh.sh
eval "$(direnv hook zsh)"
alias update="yay -Syu"
alias search="yay -Ss"
alias install="yay -S"
alias remove="yay -Rns"
alias orphans="yay -Qdt"
alias log="journalctl -b 0"
alias suspend="bash ~/bin/suspend.sh"
alias hibernate="bash ~/bin/hibernate.sh"
alias filesof="pacman -Ql"
alias packageof="pacman -Qo"
alias internet="ping google.com"
alias webserver="python3 -m http.server"
alias gradlew="./gradlew"
alias flat="flatpak --user"
alias ip="ip -color=auto"
function open() {
    nohup xdg-open "$@" > /dev/null 2>&1
}
alias paste="curl -F 'sprunge=<-' http://sprunge.us"
export BAT_THEME=ansi-light
alias cat="bat -pp"
alias less="bat"
alias done="notify-send \"Shell\" \"Done\" --expire-time 600"
alias l="exa -lah"
alias t="exa --tree"
alias t1="exa --tree -L 2"
alias t2="exa --tree -L 3"
alias t3="exa --tree -L 4"
alias t4="exa --tree -L 5"
export HISTSIZE=1000000
export HISTFILESIZE=1000000
export HISTFILE=~/.zhistory
```

**Comment by agkozak** [comment]
OK. I've found it. I recommend that you come up with another name for your alias `done`; that's an important part of a number of `zsh` control structures, and you're going to run into countless problems if you leave it the way it is. The reason `zsh-z` was loading successfully with `oh-my-zsh` was that the sourcing of `zsh-z` was occurring before the alias was being defined. Once it's defined, `zsh` can't parse most scripts.

Try renaming that or at least commenting it out for now. The sourcing problem should go away entirely. Then try experimenting with your original problem:

    /foo
    /foo/bar
    /foo/baz
    /foobar

You should be able to run `z bar` and end up in `/foo` -- on the condition that you've actually been in `/foo` itself at some point in the past. As long as `/foo` and `/foo/bar` are both in the database, you should always end up in the higher-up directory, regardless of which is ranked higher.

If you're experimenting, remember that typing `z -l bar` will show you all possible matches for the string *bar`, along with their ranks.

**Comment by agkozak** [comment]
Note: I mangled the instructions for the experiment in the last post, but I've updated them. `z foo` should get you into `/foo`, even if `/foo/bar` is ranked higher. `z bar` will take you into `/foo/bar`. I need to drink more coffee.

**Comment by piegamesde** [comment]
It still doesn't really work. When I do `z -l $FOLDER` I get a long list where `$FOLDER` is somewhere at the middle. When I then to `z $FOLDER` I'll end up in one of its subdirectories.

However, I noticed that `z -l` sometimes prints with `common: $FOLDER` as a first line. If this is the case, it will work as I'd like it to be. But it doesn't do that all the time.

**Comment by agkozak** [comment]
Yes, that's how it's supposed to work right now (thanks for catching the bug), and that's how the original `z` script works. If all of the matches start with a common string, e.g.

    /home/me/foo
    /home/me/foo/a
    /home/me/foo/b

`/home/me/foo` is what they have in common, and that's where `zsh-z` takes you. If you throw in

    /foo

then `z foo` has a match that isn't in common with all the others. Should it go to `/foo` or `/home/me/foo`? Should it go to the one you've been to most "frecently?" Should it compare the frecency of `/foo` to that of `/home/me/foo`, or should it compare `/foo` vs. all of the directories under `/home/me/foo`? It's good, I think, not to make the tool much more complicated than it already is. The original idea of `z` was that you'd type `z bin` and end up exactly where you wanted to be. If we monkey with the logic too much, a simple database such as

    /bin
    /usr/bin
    /usr/local/bin
    /home/me/bin

could result in a situation where I type `z bin`, by which I mean "Go to `bin` -- you know the one I mean" -- and instead I end up in `/usr`.

I'm sure we'll tweak the logic occasionally, and I'm open to suggestions, but I'm just trying to demonstrate how tricky it can be to improve on this sort of tool.

For now, I'll merge the recent changes to `master`.

**Comment by agkozak** [comment]
It occurs to me that I might be able to improve on the current behavior. Give me a few days, and perhaps I'll have something for you to try out.

**Comment by piegamesde** [comment]
> then `z foo` has a match that isn't in common with all the others. Should it go to `/foo` or `/home/me/foo`?

Honestly, I don't really care if `/foo` is chosen over `/home/me/foo` or not. My problem is that – following your example – I type `z foo` and end up in `/home/me/foo/a` (because I use that folder really often).

**Comment by agkozak** [comment]
Yes, I see what you mean. I'll work on this for a few days and see what I can come up with.

**Comment by piegamesde** [comment]
Thank you

**Comment by agkozak** [comment]
I'm still working on this -- I haven't forgotten. Be well.

**Comment by piegamesde** [comment]
Friendly ping

**Comment by agkozak** [comment]
Thanks!

OK. I *think* I've come up with a very simple solution to our problem. It's on the `no-subdirectories` branch. Could you switch to that and see if it works for you?

**Comment by agkozak** [comment]
I think I just improved it further. Give it another pull, if you've downloaded it already.

**Comment by piegamesde** [comment]
Thank you a lot. I'll need to test it more over time, but it already works great for my use cases.

**Comment by agkozak** [comment]
I just found a special case. My home directory is often `/home/agkozak`, but the projects I work on are naturally often like `/home/agkozak/.zinit/plugins/agkozak---agkozak-zsh-prompt` . If I type `z agk`, I definitely want to go to one of my projects, and not to the home directory, so I've introduced a little logic to work around that happening. I think in general these `z`-type utilities don't try to make it easier to get `$HOME`, when typing `cd` with no argument does that.

**Comment by piegamesde** [comment]
Yeah, this is a general problem with paths that contain multiple folders with the same name. It's not a big issue to me, but it's sensible to at least add an edge case for the home directory.

**Comment by peterjuras** [comment]
First of all I want to say thanks for providing this plugin, it's really great! 🎉 

I'm working with the `no-subdirectories` branch and it works well so far. However, I would have a question whether you would be open to prioritize exact matches over the common root path if it is provided.

Maybe this is better explained with an example:

```
$ z coat -l
3.69       /Users/juras/src/private/coat-bak
18.13      /Users/juras/src/private/coat-dev/coat/packages
28.10      /Users/juras/src/private/coat-dev/cli-integration-tests-template
75.89      /Users/juras/src/private/coat-dev
301        /Users/juras/src/private/coat-dev/coat
1492.51    /Users/juras/src/private/coat-dev/coat/packages/cli
$ z coat -e
/Users/juras/src/private/coat-dev
```

The above output shows the directory listing for the `z coat -l` and `z coat -e` commands. The `no-subdirectories` logic already improves my expectations for entering `z coat`, since it brings me to the `/Users/juras/src/private/coat-dev` directory instead of the `/Users/juras/src/private/coat-dev/coat/packages/cli` folder.

However, I would prefer it even more if the `z coat` command would take me to `/Users/juras/src/private/coat-dev/coat` since it is the exact match of the folder I would like to change into.

Of course this might also just be personal preference, but I tried to think of more cases and it seems to me that prefering exact matches of the name of a folder that ends the path might be desirable behavior for more users.

**Comment by agkozak** [comment]
@peterjuras You're exactly right, and thanks for putting it so clearly. That is how it will work eventually. What I've got in place right now is just a stopgap until I code it properly.

**Comment by agkozak** [comment]
I have just rewritten the new routine so that it drops path elements from the right until doing so would change the number of times the search pattern appears in the best match. If the best match is (as in @peterjuras's example)

    /Users/juras/src/private/coat-dev/coat/packages/cli

then `z coat` should take you to `/Users/juras/src/private/coat-dev/coat`, not `/Users/juras/src/private/coat-dev`.

There's still a problem that we inherit from `rupa/z`: the notion of the "common directory." If @peterjuras had not had `/Users/juras/src/private/coat-bak` in his database, `/Users/juras/src/private/coat-dev` would have been the common directory for `z coat`, and it would be chosen in place of any of the directories under it.

I'll probably experiment a bit with ignoring the "common directory" and seeing how well that works out. I suspect I'm eventually going to bundle up what we're working on here either as an optional behavior for ZSH-z or as a new default, with the old behavior still available for those who want it. Please keep letting me know what you think.

**Comment by agkozak** [comment]
@piegamesde @peterjuras I'm happy enough with how the new, alternate behavior works that I've merged it onto the `master` branch, so you may go back to using that, but be sure to set `ZSHZ_UNCOMMON=1` in your `.zshrc` to make it kick in.

Thanks very much, both of you, for helping to improve ZSH-z.

**Comment by nietaki** [comment]
I had the same problem as OP where some of my most used directories were 
```
~/repos
~/repos/foo
~/repos/bar
~/repos/baz
```
but running `z repos` always got me into one of the subdirectories, instead of the matching containing directory. Adding `ZSHZ_UCOMMON=1` to my `.zshrc` seems to have helped.

I'm glad I decided to look through the closed issues before raising a new one with a question :)

**Comment by agkozak** [comment]
@nietaki I'm so glad you found the closed issues to be helpful - they're meant to be. I intend to rewrite the`README.md` soon to highlight some of these common questions.
