### ISSUE TITLE
Fantasic script, works great with zimfw

### ISSUE THREAD

**Issue by keybits** [agkozak/zsh-z#15]
Thanks for your work on this. I've selected it over z, autojump and pazi.

I'm using [zimfw](https://github.com/zimfw/zimfw) and zsh-z works great by cloning into `.zimfw/modules/zsh-z` and then enabling it as a module in `.zimrc`.

I did need to add `autoload -U compinit && compinit` to `.zshrc` for tab autocompletion.

Your delightfully helpful approach on the few issues I saw here was the clincher for installing. Thanks again and feel free to close this issue.

**Comment by agkozak** [comment]
Thank you so much for you kind words. I'll make a point of including instructions for how to use zsh-z with Zim.

**Comment by agkozak** [comment]
Done! Thanks again for your encouragement and for helping to make zsh-z better.
