### ISSUE TITLE
Not working on Arch Linux

### ISSUE THREAD

**Issue by Thiago4532** [agkozak/zsh-z#18]
z plugin stopped working on my zsh. When I type "zsh -e directory" it prints nothing and z command is working like cd command. I can't jump to a specific folder using it.

**Comment by agkozak** [comment]
Try

    cat ~/.z

and see what it prints out.

Also, could you post your `.zshrc`? Thanks.

**Comment by Thiago4532** [comment]
I solved. I deleted the .z  file and started to work again. I'll try to discover why my .z file was not working before..

**Comment by Thiago4532** [comment]
Ok. I don't know what's happening, but it's working now, thanks!! :D
