### ISSUE TITLE
z overwrites symlinks

### ISSUE THREAD

**Issue by therealmaxmoon** [agkozak/zsh-z#19]
I keep important dotfiles in a git repository and link to them from my home directory, like

`ln -s ~/my_git_repos/dotfiles/.z ~/.z`

The database gets always overwritten by z every time it is executed successfully. 

It would be nice if z could follow symlinks instead of overwriting them.

**Comment by agkozak** [comment]
You're write - it should work that way, but there's a bug. I'll fix it.

In the meantime, if you set `ZSHZ_DATA="$HOME/my_git_repos/dotfiles/.z"`, that should fix your problem.

I'll let you know when I've fixed the bug.

**Comment by agkozak** [comment]
@therealmaxmoon, thank you for your patience!

I have just pushed a fix to the `develop` branch. Please back up your datafile and then give that branch a try. Let me know if it fixes your problem. Thanks!

**Comment by agkozak** [comment]
The bug fix is now part of the `master` branch, so I'm going to close this issue, but do let me know if you need anything else.
