### ISSUE TITLE
Use add-zsh-hook

### ISSUE THREAD

**Issue by z0rc** [agkozak/zsh-z#2]
Instead of doing
https://github.com/agkozak/zsh-z/blob/7997b35162f8308cbbe5f07d53d30bea75314bb4/zsh-z.plugin.zsh#L536-L545
You can autoload and call [add-zsh-hook](https://github.com/zsh-users/zsh/blob/master/Functions/Misc/add-zsh-hook) to handle this.

**Comment by agkozak** [comment]
You're right! It's much more elegant to do it that way, and it works on ZSH v4.3.11, which is the oldest version I'm supporting.

I've pushed [a commit](https://github.com/agkozak/zsh-z/commit/e3a36624a7324ab73cc2d828fa8964325384faa0) for this to the `develop` branch; it should be on master soon.

Thank you so much for contributing your idea.
