### ISSUE TITLE
z consumes CPU and does not work on the experimental no-subdirectories branch

### ISSUE THREAD

**Issue by piegamesde** [agkozak/zsh-z#21]
Sometimes, z doesn't really work. It will burn through one CPU core doing things, without actually entering the directory. The interesting thing is, that `z -l` does not have this problem and instantly lists me the results. `z -e` suffers from the problem again. It also depends on the used query. I don't know if it ever terminates when the bug occurs, the longest I've tried was about half an hour.

I'm on the subdirectories branch, so it may be related to this.

**Comment by agkozak** [comment]
Interesting. I ran into that problem when I was cobbling together the **(still unfinished; wait for more soon)** `no-subdirectories` branch, but I thought I had fixed it.

First, confirm that you're on the most recent commit (`f9e2d3e`).

Then, find a query that produces that result, and try to give me an idea of what's in your database for that query (use `z -l <query>`).

Thanks very much for your help.

**Comment by piegamesde** [comment]
> First, confirm that you're on the most recent commit (f9e2d3e).

Hm, that's difficult to say because I forgot to pin the version, but since the latest commit is almost three weeks ago the probability of having used an older cached version is neglectable to me.

There is only one folder displayed with `z -l` (in one of the queries that break the extensions, others may have up to a dozen). The interesting part to me is that if the query is correctly capitalized, it works instantly. The listing is the same regardless of the capitalization, but when actually jumping into the directory there suddenly is a difference.

**Comment by agkozak** [comment]
Try going to the directory where ZSH-z is kept and type

    git log

The top entry should be

    commit f9e2d3ec1d5c83c377601a0b0d12f402213155ff

and the comment should be

    Variable name; documentation

Thanks. I just want to make sure I'm not fixing something that's already been fixed.

**Comment by agkozak** [comment]
Never mind. I see what you're talking about. It seems to happen, as you say, when I say

    z foo

and `/path/to/Foo` (capitalized) exists.

I'll work on this. Sorry I haven't been more active lately; I need new eyeglasses, and the pandemic lockdown is getting in the way of their being made.

**Comment by agkozak** [comment]
OK. I think I've got it working for case-insensitive queries again. Give the latest commit to `no-subdirectories` a try. Let me know if it works for you.

(I'm also circumventing the "go to a common root" behavior on this branch, since we probably don't want it. I'll explain in more detail on the page for the original feature request. Eventually I'll probably package all of this up as an optional set of behaviors and leave the original behavior as default for people who are used to `rupa/z`.)

**Comment by piegamesde** [comment]
Works for me, thank you.

**Comment by agkozak** [comment]
Thank you for your help!
