### ISSUE TITLE
`-l` updates the timestamp

### ISSUE THREAD

**Issue by tekumara** [agkozak/zsh-z#24]
Running `z code -l` will update the timestamp of the winning `code` entry, and therefore its score, which I found surprising.

I was expecting this operation to be non-destructive because it doesn't change the current directory, unlike `z code`.

**Comment by agkozak** [comment]
ZSH-z (like `rupa/z`) updates its database every time a prompt is drawn. The database largely represents not the directories you go to, but the directories you spend your time in the most. So running any command at all will cause the rank of the directory you are in to go up, while all the other directories in the database "age" (they grow gradually smaller).

**Comment by tekumara** [comment]
Oh right I can see that when I'm in `/tmp` and run `z code -l` repeatedly, the scores for the `code` directories go down. Presumably, because I'm spending more time in `/tmp`.

**Comment by agkozak** [comment]
Yes. The idea is that if I go to `/foo` and spend a minute in it, and then I switch to `/bar` and spend a day there -- `/bar` should greatly outrank `/foo`, right?
