### ISSUE TITLE
[Question] How do I reduce the max size of the zsh-z database file?

### ISSUE THREAD

**Issue by surmish** [agkozak/zsh-z#26]
I am trying to speed up my zsh prompt. I think updating zsh-z does take some time on slower machines leading to slow behavior. Does changing ZSH_MAX_SCORE help?

Also, is there an async mode for this plugin?

**Comment by agkozak** [comment]
You're right -- ZSH-z naturally does take a *little* time to do its job. But to answer your last question first, ZSH-z, like the original `z.sh` itself, always runs asynchronously. The task that runs every time a prompt is drawn is

    (zshz --add "${PWD:A}" &)

The `&` causes ZSH-z to run in a background task. On a really slow system, which is to say anything that's Windows underneath (MSYS2, Cygwin, WSL), even launching that background task is a bit slow -- but once it's been launched, everything takes place in the background.

On non-Windows systems, the difference between running ZSH-z and not running it is often negligible -- it's really very fast.

Now, by setting `ZSHZ_MAX_SCORE` to a lower number, you can make ZSH-z start "aging" your database sooner. That might very well have the effect of speeding up how quickly your less frequently used paths drop out of the database. I would not, however, expect that to speed things up very much at all. ZSH-z is extremely efficient, and, as I noted, database management does take place in the background. A smaller database is unlikely to make things noticeably faster.

Could you give me some examples of slower systems that you're using where you suspect ZSH-z is slowing you down? If I can simulate something like one of them, I'd be happy to run some benchmarks. Just let me know the operating system and the sort of computer system it's running on.

**Comment by surmish** [comment]
So I dived a little deeper and it looks like this is not an issue. I had other plugins which were taking time to load on every prompt. I will switch to a simpler prompt too.
