### ISSUE TITLE
Completion of `-c` option not working. 

### ISSUE THREAD

**Issue by jonathangreen** [agkozak/zsh-z#27]
The [improvements section](https://github.com/agkozak/zsh-z#improvements-and-fixes) notes that:
> Completions work with options -c, -r, and -t.

But the completions with these options aren't working for me. Taking a look at the completions file, it seems like [this line](https://github.com/agkozak/zsh-z/blob/master/_zshz#L56-L57):
```zsh
# Don't try to complete a string beginning with a hyphen
[[ ${(@)words:1} == -* ]] && return 1
```

Is stopping these completions from working. Is something wrong with my setup, or are these completions not supported?

Thank you for both your help and the great zsh plugin!

**Comment by agkozak** [comment]
Good catch! I included that line as a stopgap while working on something else, and I forgot to get back to it.

You can comment out that line for now; I'll have the original problem fixed in a day or two and push it to `master`.

Thank you so much!

**Comment by jonathangreen** [comment]
Once I commented out that line, my autocomplete works, but the command once autocompleted fails to actually change to the selected directory. 

For example something like this: 
```
~$ z pro
~/project$ z -c prod
[hit tab]
pick the tab completion for: 
/home/me/project/env/prod
~/project$ z -c /home/me/project/env/prod
~/project$ echo $?
1
```

When I hit tab, it completes okay, but it then won't accept that argument.

**Comment by agkozak** [comment]
Thanks. I'll get to work on this.

**Comment by agkozak** [comment]
If you try the branch `current-completion`, you'll find that I've put together a quick fix that should work for now. Let me know if it works for you.

**Comment by jonathangreen** [comment]
Works great. Thanks for the quick update!

**Comment by agkozak** [comment]
This feature is on the `master` branch now, so you can switch back to that. Thanks for helping to make this plugin better.
