### ISSUE TITLE
`z -l` output format compatability

### ISSUE THREAD

**Issue by z0rc** [agkozak/zsh-z#3]
I tried to enable [fzf-z](https://github.com/andrewferrier/fzf-z) with this plugin. But seems it isn't quite compatible. There is one issue where fzf-z expects `z -l` output to show rank with `.` delimiter, where this plugin uses `,`. See sed match from https://github.com/andrewferrier/fzf-z/blob/master/fzf-z.plugin.zsh#L54

**Comment by agkozak** [comment]
You've identified the problem quite well - it's a simple problem of locale. Your machine is probably set up to display decimal fractions with a comma, and ZSH-z respects that.

I'll try out `fzf-z` later today and come up with a fix or workaround for you.

**Comment by z0rc** [comment]
Interesting. Can you point me to where zsh-z uses locale's number formatting? I might be able to fix this on my side.

**Comment by agkozak** [comment]
Try putting

    alias z='LC_ALL=C zshz 2>&1'

into your `.zshrc` file, somewhere below where you source or load the ZSH-z plugin. That will make the `z` alias override the system's default preferences. Let me know if that works; it did for me.

The problem arises in [a `printf` statement](https://github.com/agkozak/zsh-z/blob/3b0be0e0b91097e4e7b8ecc1938352ad3e702a49/zsh-z.plugin.zsh#L384), I think. You can probably reproduce the behavior at your command line by typing

    printf '%.2f\n' 33.33333

Whether or not the output is `33.33` or `33,33` depends on your locale.

I'll think about a long-term solution; compatibility with `rupa/z` is extremely important, although it is nice to respect people's national preferences, too. Perhaps including instructions about that alias would be a nice compromise. I'll think about. In the meantime, let me know if it works.

**Comment by z0rc** [comment]
Awesome. I fixed this on my side. The situation was like this:
```
% locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=uk_UA.UTF-8
LC_TIME=C
LC_COLLATE=C
LC_MONETARY=uk_UA.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=uk_UA.UTF-8
LC_NAME=uk_UA.UTF-8
LC_ADDRESS=uk_UA.UTF-8
LC_TELEPHONE=uk_UA.UTF-8
LC_MEASUREMENT=uk_UA.UTF-8
LC_IDENTIFICATION=uk_UA.UTF-8
LC_ALL=
                                                                                                                                                                                               
~
% printf '%.2f\n' 33.33333
33,33
                                                                                                                                                                                               
~
% LC_NUMERIC=C printf '%.2f\n' 33.33333
33.33
                                                                                                                                                                                               
~
% LC_ALL=C printf '%.2f\n' 33.33333
33.33
```

So zsh follows LC_NUMERIC and LC_ALL when formatting the numbers. I'm switching to `LC_NUMERIC=C`. This resolves my problem, but maybe it's worth documenting. Also I'm really not sure how `rupa/z` behaves at this case, as I didn't try it.

**Comment by agkozak** [comment]
Thanks so much for your research! You've helped me to improve my script.

I've decided to use the period as the decimal separator in all locales -- it's important if I want ZSH-z to continue to be a drop-in replacement for `rupa/z`. So now you shouldn't need to use an alias. Let me know if you run into any other problems.
