### ISSUE TITLE
Case-insensitive "z"

### ISSUE THREAD

**Issue by zachriggle** [agkozak/zsh-z#30]
It would be nice if the standard invocation of "z" were case-insensitive.

```sh
$ z -l | grep -i foo
15.99      /Users/zachriggle/foob
23.98      /Users/zachriggle/FOOa
```

I would assume that `z foo` takes me to `FOOa` but it does not.  

```sh
$ z foo
$ pwd
/Users/zachriggle/foob
```

There does not seem to be an option to enable this, based on my quick perusal of `zsh-z.plugin.zsh` (which is how I found out that the tab-complete is case-insensitive)

Interestingly, specifying the full name (such that there are no other matches) works as you'd expect.

```sh
$ z fooa
$ pwd
/Users/zachriggle/FOOa
```

TL;DR: `FOOa`, being the highest ranked option which matches the query "foo" case-insensitively, should be used (or at least have an option to be used).  This is especially the case for macOS users since the entire filesystem is case-insensitive anyway.

It looks like internally, Z checks for both case-sensitive matches and case-insensitive matches:

```sh
    if [[ $path_field == ${~q} ]]; then
      matches[$path_field]=$rank
    elif [[ ${path_field:l} == ${~q:l} ]]; then
      imatches[$path_field]=$rank
    fi
```

But it gives precedence to case-sensitive matches:

```sh
  # Return 1 when there are no matches
  [[ -z $best_match ]] && [[ -z $ibest_match ]] && return 1

  if [[ -n $best_match ]]; then
    _zshz_output matches best_match $format
  elif [[ -n $ibest_match ]]; then
    _zshz_output imatches ibest_match $format
  fi
```

**Comment by zachriggle** [comment]
I was able to implement this locally by switching the order of the `if/elif` that prints `_zsh_output`.  I cannot contribute a patch due to restrictions by my employer, unfortunately.

**Comment by agkozak** [comment]
I have been struggling with an eyesight problem and am only just getting used to my new eyeglasses. Expect more from me soon. Thanks for your patience.

**Comment by fharper** [comment]
I would love that option also!

**Comment by ratijas** [comment]
Just for the reference.  There is such thing as a "smart case search", although you probably won't find it under that name on google.

The idea is to use case-insensitive lookup by default, falling back to case-sensitive matching only when the search term (query) contains mixed (upper- and lower-case) characters. Algorithmically speaking, it goes like this:

```python
# mix of Python and C
search_variant = (
  len(term) > 1 and
  any(map(isupper, term)) and
  any(map(islower, term))
) ? CASE_SENSITIVE : CASE_INSENSITIVE;
```

**Comment by agkozak** [comment]
Thanks, everybody.

The default matching behavior of ZSH-z is what it inherited from `rupa/z`: always match case-sensitively when possible; failing that, try case-insensitively.

The behavior @zachriggle describes is that of the `ignorecase` setting familiar to those of us who use Vim. What @ratijas describes is what you get in Vim when you also `set smartcase`, and it's what I prefer myself. I think that I can easily implement both and have the alternate behaviors enabled with an environment variable setting. Please give me a few days to get something working on a branch, and then I'll have everyone give the new features a try.

**Comment by fharper** [comment]
Wonderful, thanks @agkozak !

**Comment by agkozak** [comment]
OK, I threw something together quickly on the `case` branch. Try switching to that branch.

If you set

    ZSHZ_CASE=ignore

then all pattern-matching should be case-insensitive.

If you set

    ZSHZ_CASE=smart

then patterns that are lowercase are treated case-insensitively, whereas ones that have uppercase characters in them cause case-sensitive matches to be privileged.

So with smartcase, if you have the directories

    /foo/audacity
    /bar/Audio-Technica

`z au` will match whichever is more "frecent" and `z Au` will match `/bar/Audio-Technica`. If you type `z AU`, though, I'm going to have it pick whichever is more frecent -- for now I think I'll have it always fall back to case-insensitivity rather than rejecting the pattern.

Let me know what you think.

**Comment by agkozak** [comment]
> If you type `z AU`, though, I'm going to have it pick whichever is more frecent -- for now I think I'll have it always fall back to case-insensitivity rather than rejecting the pattern.

Actually, as I play around with `ZSHZ_CASE=smart`, I'm beginning to think that, in that example, `z AU` should fail. One uses capital letters for a reason. I'll make the change tomorrow.

**Comment by agkozak** [comment]
OK, I've got smartcase working more strictly now.

**Comment by fharper** [comment]
Awesome, can't wait to try this, thanks a lot @agkozak !

**Comment by agkozak** [comment]
`ZSHZ_CASE`, with the settings `ignore` and `smart`, is now part of the `master` branch. Thank you all for helping to improve this plugin.
