### ISSUE TITLE
Broken Tab Completion

### ISSUE THREAD

**Issue by rwtallant13** [agkozak/zsh-z#41]
I think my tab completion is broken. Not sure if its a problem with my zsh config or some sort of bug/error. 

![zsh-z-tabcomplete](https://user-images.githubusercontent.com/10453230/116964561-5de30700-ac9b-11eb-89e1-f7cea3f023d0.gif)

here is my .zshrc if you see something that might be causing it. https://termbin.com/zp1k

**Comment by agkozak** [comment]
This one's a little difficult, isn't it? Could you try something for me? It seems to work for me.

Comment out

    setopt complete_aliases

and change

    autoload -Uz compinit && compinit -C -d "$XDG_CACHE_HOME"/zsh/zcompdump-$ZSH_VERSION

to

    autoload -U compinit && compinit

That fixed it for me, though I haven't had enough coffee yet to figure out why. If it works for you, we can try to figure out what's going wrong.

**Comment by rwtallant13** [comment]
That fixed it for me too. I started messing around with it a bit and after deleting my old zcompdump and removing complete_aliases it seems to work fine now with the same autoload/compinit commands i was using before. Not exactly sure where the problem came from but it works now and that's good enough for me. Thanks
