### ISSUE TITLE
Echo directory when switching

### ISSUE THREAD

**Issue by rwtallant13** [agkozak/zsh-z#42]
z.lua which i briefly used had this option and i found it handy, would love to see this implemented here as well if possible.

**Comment by agkozak** [comment]
That sounds like a great idea to me. I'll add an option. Would you be willing to help me test it out in a few days? Thanks.

**Comment by rwtallant13** [comment]
Absolutely just let me know when

**Comment by agkozak** [comment]
I put a version in the `echo` branch that I think should do what you want. Just install it and set

    ZSHZ_ECHO=1

and you'll see the new paths as you switch to them.

Let me know if that is more or less what you were looking for.

**Comment by rwtallant13** [comment]
this works perfectly! exactly what i was looking for. Thank you!

**Comment by agkozak** [comment]
Great. Keep using it and let me know if you see any glitches. I'll do the same; I'll let you know when I merge it to `master`.

**Comment by rwtallant13** [comment]
Will do. Thanks again.

**Comment by agkozak** [comment]
We can leave this issue open till I've merged the new feature. Thanks again for contributing the good idea.

**Comment by agkozak** [comment]
All right. The new feature is on the `master` branch now. You can switch to that. Thanks again.
