### ISSUE TITLE
Declare ZSHZ_EXCLUDE_DIRS so that it can be appended to

### ISSUE THREAD

**Issue by zachriggle** [agkozak/zsh-z#44]
I have conditionals and multiple scripts (in multiple places) where I want to add entries to `ZSHZ_EXCLUDE_DIRS`.

The main script should:

```bash
declare -ga ZSHZ_EXCLUDE_DIRS=( )
```

So that these scripts can all just append to the array, rather than having to rely on one of them to create the array, and the others to append to it, e.g.:

```bash
ZSHZ_EXCLUDE_DIRS+=( foo bar )
```

So that other scripts don't need to check for its existence.

```bash
if [ -z "${ZSHZ_EXCLUDE_DIRS[*]}" ]; then
  declare -ga ZSHZ_EXCLUDE_DIRS
fi

ZSHZ_EXCLUDE_DIRS+=( fizz buzz )
```

**Comment by agkozak** [comment]
This is a great idea. Many thanks. I'll add the code in just a few days - I'm finishing up a huge project today and tomorrow.

**Comment by agkozak** [comment]
I've made the addition on the `exclude-dirs` branch; make sure it does what you want, and I'll merge it to `master`. Thanks again.

**Comment by zachriggle** [comment]
Looks good to me!

```diff
diff --git a/zsh-z.plugin.zsh b/zsh-z.plugin.zsh
index 77c10d4..57ebec4 100644
--- a/zsh-z.plugin.zsh
+++ b/zsh-z.plugin.zsh
@@ -108,6 +108,10 @@ With no ARGUMENT, list the directory history in ascending rank.
 # Global associative array for internal use
 typeset -gA ZSHZ

+# Make sure ZSHZ_EXCLUDE_DIRS has been declared so that other scripts can
+# simply append to it
+(( ${+ZSHZ_EXCLUDE_DIRS} )) || typeset -ga ZSHZ_EXCLUDE_DIRS
+
 # Determine if zsystem flock is available
 zsystem supports flock &> /dev/null && ZSHZ[USE_FLOCK]=1
```

**Comment by agkozak** [comment]
@zachriggle Thanks for the great suggestion! I'm merged this improvement to the `master` branch.
