### ISSUE TITLE
_zshz_find_matches:68: error in flags

### ISSUE THREAD

**Issue by ravenxrz** [agkozak/zsh-z#47]
I installed this plugin on my mac and centos 7 manually. Both use the same config.
But mac runs perfectly, centos not, and leaves "_zshz_find_matches:68: error in flags" message on my terminal.
Any idea to fix this? Thx in advance.

**Comment by agkozak** [comment]
Thanks for reporting this error.

Could you confirm for me the version of ZSH you're using on CentOS? You can find that easily by typing

    echo $ZSH_VERSION

Thanks!

**Comment by agkozak** [comment]
It looks to me as if [a patch introduced a while back](https://github.com/agkozak/zsh-z/pull/43) uses a flag that only works in newer versions of ZSH. I am keen, however, to keep ZSH-z working with ZSH versions going back as far as 4.3.11, so if you give me a few days, I'll come up with a way to do the same thing without using that flag.

**Comment by agkozak** [comment]
Try what I just put on the `ecaped_path_field` branch to see if it fixes your problem.

**Comment by ravenxrz** [comment]
> Thanks for reporting this error.
> 
> Could you confirm for me the version of ZSH you're using on CentOS? You can find that easily by typing
> 
> ```
> echo $ZSH_VERSION
> ```
> 
> Thanks!

the version is 5.0.2 on CentOS.



> Try what I just put on the `escaped_path_field` branch to see if it fixes your problem.

Cool!  everything works fine now. Thank you for this amazing plugin.

**Comment by agkozak** [comment]
@ravenxrz Thanks for your feedback. I have merged the changes to `master`, so you may switch back to using that.
