### ISSUE TITLE
ZSHZ_NO_RESOLVE_SYMLINKS does not work

### ISSUE THREAD

**Issue by piegamesde** [agkozak/zsh-z#5]
I set `export ZSHZ_NO_RESOLVE_SYMLINKS=1` in my `.zshrc`, but when I cd into a symlink, it still adds the path behind the symlink to the history and not the symlink itself.

**Comment by agkozak** [comment]
That's funny -- it works for me. What operating system are you using? Thanks!

**Comment by piegamesde** [comment]
I'm on Arch Linux. I installed `zsh-z` simply by adding the `z` plugin to my `~/.zshrc`.

**Comment by agkozak** [comment]
Let me describe what it looks like when I say it works for me, and perhaps you can tell me how things differ on your system.

I create a directory `realdirectory` and `cd` in and out of it to add it to the zsh-z database:

    cd ~
    mkdir realdirectory
    cd realdirectory
    cd ..

If I type

    z reald<TAB>

It should fill in

    z /path/to/realdirectory

for me.

Now I'll create a symlink to `realdirectory`:

    ln -s ~/realdirectory ~/symlink

If I `cd` in and out of it

    cd ~
    cd symlink
    cd ..

without having set `ZSHZ_NO_RESOLVE_SYMLINKS=1`, when I type

    z syml<TAB>

I get nothing (unless there's already something like that in the database, of course).

If I start up a fresh instance of `zsh` like this:

    ZSHZ_NO_RESOLVE_SYMLINKS=1 zsh

I can do the necessary steps to add the symlink to the database

    cd ~
    cd symlink
    cd ..

If I type

    z syml<TAB>

It should complete `z /path/to/symlink` for me.

Try those steps and tell me where your experience differs. Thanks!

**Comment by piegamesde** [comment]
> If I type
> z syml<TAB>
> It should complete z /path/to/symlink for me.

That's where our experiences diverge. I executed exactly the same commands, and `z -l` contains `~/realdirectory` but not `~/symlink`. If I remove `~/realdirectory` and `cd` into `symlink`, it will still add `~/realdirectory` to the history.

**Comment by agkozak** [comment]
Got it. I'll give this some thought and play around with it in Arch.

Could you

    echo $ZSHZ_NO_RESOLVE_SYMLINKS

just to be certain sure that it's been set to `1`? It's acting as if that hasn't happened for some reason.

Did you use to use `rupa/z`? Is `$_Z_NO_RESOLVE_SYMLINKS` set in your `.zshrc`? It shouldn't matter, but perhaps it's worth asking.

**Comment by agkozak** [comment]
And could you check one very important thing? With `ZSHZ_NO_RESOLVE_SYMLINKS` set to `1`, type

    which _zshz_precmd

The output should be

    _zshz_precmd () {
            (( ! ZSHZ[directory_removed] )) && (
                    zshz --add "${PWD:a}" &
            )
            : $RANDOM
    }

`${PWD:a}` is what we're looking for. If it's `${PWD:A}`, that's the problem. Thanks!

**Comment by piegamesde** [comment]
```
~ » echo $ZSHZ_NO_RESOLVE_SYMLINKS
1
~ » which _zshz_precmd
_zshz_precmd not found
```

**Comment by agkozak** [comment]
> ~ » which _zshz_precmd
> _zshz_precmd not found

Wow! That's probably our problem. Without `_zshz_precmd`, nothing new gets added to your `~/.z` database at all.

Could you try

    echo $precmd_functions

for me? I want to see if the hook is being added, just so I can see how badly this thing is misfiring.

**Comment by piegamesde** [comment]
```
~ » echo $precmd_functions
omz_termsupport_precmd _z_precmd
```

> Wow! That's probably our problem. Without _zshz_precmd, nothing new gets added to your ~/.z database at all.

If nothing gets added at all, how does it still work for non-symlinks then?

**Comment by agkozak** [comment]
> ```
> ~ » echo $precmd_functions
> omz_termsupport_precmd _z_precmd
> ```
> 
> 
> > Wow! That's probably our problem. Without _zshz_precmd, nothing new gets added to your ~/.z database at all.
> 
> 
> If nothing gets added at all, how does it still work for non-symlinks then?

Since you've got the `_z_precmd` hook and you don't have `_zshz_precmd`, I'm going to conclude that you're still running the old `z`, not `zsh-z`. You might want to check your `.zshrc` carefully to see why that is. If you want to share it, I'll be happy to take a look.

**Comment by piegamesde** [comment]
I was indeed running `z` instead of `zsh-z`. After following the installation instructions, it now works as intended. Sorry for wasting your time.

**Comment by agkozak** [comment]
No problem at all! It was actually good for me to go through the steps of discovering the source of the confusion -- I suspect I'll run into this situation again, and I'll know what to look for next time. Be well!
