### ISSUE TITLE
zsh-z not following description format 

### ISSUE THREAD

**Issue by AtifChy** [agkozak/zsh-z#51]
this is how my completion description look
![image](https://user-images.githubusercontent.com/42291930/129333591-fc14dc90-165d-48ab-99a3-12133ec1159c.png)

but with zsh-z it's just white text. It's not following my description format
![image](https://user-images.githubusercontent.com/42291930/129333741-ce6f0c00-681e-4e93-bba0-c259e70d5651.png)

my completion description format
```zstyle ':completion:*:descriptions' format '%U%B%F{cyan}%d%f%u'```

**Comment by agkozak** [comment]
Could you post your whole `.zshrc` or provide a link to it? Thanks.

**Comment by agkozak** [comment]
> zstyle ':completion:*:descriptions' format '%U%B%F{cyan}%d%f%u'

That should have a `%b` in it: `zstyle ':completion:*:descriptions' format '%U%B%F{cyan}%d%f%b%u'` But that's not the problem. I'll figure this out.

**Comment by AtifChy** [comment]
> Could you post your whole `.zshrc` or provide a link to it? Thanks.

https://github.com/AtifChy/dotfiles/blob/main/.config/zsh/.zshrc

**Comment by agkozak** [comment]
I'm on the verge of solving this. Give me just a little time.

**Comment by agkozak** [comment]
@AtifChy OK. I've got a proposed fix on the `description` branch. Please give it a try and tell me if it works for you.

Thanks so much, by the way, for bringing this matter up. It gives me an opportunity to improve the plugin.

**Comment by AtifChy** [comment]
> @AtifChy OK. I've got a proposed fix on the `description` branch. Please give it a try and tell me if it works for you.

it works
> 
> Thanks so much, by the way, for bringing this matter up. It gives me an opportunity to improve the plugin.

my pleasure

**Comment by agkozak** [comment]
All right, I've merged the changes to the `master` branch, so you may switch back to that. Thanks again.
