### ISSUE TITLE
Integrating with ranger

### ISSUE THREAD

**Issue by ask1234560** [agkozak/zsh-z#55]
Hi,
I was a user of [z](https://github.com/rupa/z), thank you for creating this project.

I had created a jumper for ranger using [z](https://github.com/rupa/z), [this](https://github.com/ask1234560/ranger-zjumper). The current implementation uses  python regex for searching the pattern in the z file.

Is there any way i can use your project as standalone command in python subprocess, like `z -e directory-name`.

**Comment by agkozak** [comment]
(The file format is identical to that of `rupa/z`, so I think we can get your plugin working for people regardless of which shell or tool they're using.)

**Comment by agkozak** [comment]
Ah, `subprocess.run()` works with the same arguments.

**Comment by ask1234560** [comment]
Thanks you,

`subprocess.check_output(['zsh', '-c', 'source /path/to/zsh-z.plugin.zsh && zshz'])`

It worked, this is exactly what i was looking for.

**Comment by ask1234560** [comment]
Is there any way to get file location of zsh-z.plugin.zsh. From environment or something.

**Comment by ask1234560** [comment]
The below one is working as expected with lesser lines of code. The only thing remaining is to dynamically find the location of zshz source file.
````
import ranger.api
from ranger.api.commands import *
from subprocess import check_output


class z(Command):
    """:z
    Uses .z file to set the current directory.
    """

    def execute(self):
        try:
            arguments = 'source /home/ananthu/.config/.zplug/repos/agkozak/zsh-z/zsh-z.plugin.zsh && zshz -e ' + \
                " ".join(self.args[1:])
            directory = check_output(
                ['zsh', '-c', arguments]).decode().rstrip("\n")
            self.fm.execute_console("cd " + directory)
        except Exception as e:
            raise Exception("Directory not found")

**Comment by ask1234560** [comment]
Yeah i was also thinking of creating a environment variable pointing to the script. Thank you for helping.

**Comment by agkozak** [comment]
> Yeah i was also thinking of creating a environment variable pointing to the script. Thank you for helping.

That sounds like a great idea. Good luck!
