### ISSUE TITLE
Feature: "zshz --add $dir" should increase its rank by at least 1

### ISSUE THREAD

**Issue by zachriggle** [agkozak/zsh-z#57]
It seems like increasing the rank by at least 1 for existing directories would be a good idea.

I've got a few hundred directories tracked by zshz, many are all at score 1, and executing any number of commands in them (interactive or in a loop) doesn't seem to increase the score at all.

It would seem that doing e.g.

```sh
for i in {1..100}; do zshz --add $PWD; done
```

Should bump up the score to at least 3, but it does not :(.

**Comment by agkozak** [comment]
That's a bug. Give me a little while and I'll fix it. Thanks, @zachriggle!

**Comment by agkozak** [comment]
OK. Give your `no-age` branch a pull and see if that fixes it.

**Comment by zachriggle** [comment]
Here's my commit history with the merge:

```
$ glg -n 10
*   d04e99a - (HEAD -> master) Merge branch 'no-age' of https://github.com/agkozak/zsh-z (3 minutes ago) - Zach Riggle
|\
| *   ce15243 - (upstream/no-age) Merge branch 'bugfix' into no-age (71 minutes ago) - Alexandros Kozak
| |\
| | * 5c13e5d - rank was not incrementing during --add (72 minutes ago) - Alexandros Kozak
| * |   5a144c7 - Merge branch 'develop' into no-age (2 days ago) - Alexandros Kozak
| |\ \
| | * | 986f088 - Documentation (2 days ago) - Alexandros Kozak
| | * | 7f275aa - (upstream/add-relative-paths) Path fix for Cygwin/MSYS2 (2 days ago) - Alexandros Kozak
| | * | efcba57 - Add relative paths (but fix for MSYS/Cygwin/etc.) (2 days ago) - Alexandros Kozak
| | |/
| | * b1055fb - Zdharma link (13 days ago) - Alexandros Kozak
| | * 25f780f - Zdharma links (13 days ago) - Alexandros Kozak
| | * 9eb7b94 - Sort completions by rank, not alphabetically (4 weeks ago) - Alexandros Kozak
```

It doesn't look like it worked 😢 

```
$ pwd
/Users/zachriggle/zshz-add-test

$ z -l zshz-add-test
2          /Users/zachriggle/zshz-add-test

$ zshz --add $PWD/a

$ zshz --add $PWD/b

$ z -l zshz-add-test
common:    /Users/zachriggle/zshz-add-test
1          /Users/zachriggle/zshz-add-test/a
1          /Users/zachriggle/zshz-add-test/b
2          /Users/zachriggle/zshz-add-test

$ zshz --add $PWD/a

$ zshz --add $PWD/a

$ zshz --add $PWD/a

$ z -l zshz-add-test
common:    /Users/zachriggle/zshz-add-test
1          /Users/zachriggle/zshz-add-test/b
2          /Users/zachriggle/zshz-add-test
2          /Users/zachriggle/zshz-add-test/a

$ zshz --add $PWD/a

$ z -l zshz-add-test
common:    /Users/zachriggle/zshz-add-test
1          /Users/zachriggle/zshz-add-test/b
2          /Users/zachriggle/zshz-add-test
2          /Users/zachriggle/zshz-add-test/a

$ wc -l ~/.z
     646 /Users/zachriggle/.z
```

**Comment by agkozak** [comment]
> $ z -l zshz-add-test
> common:    /Users/zachriggle/zshz-add-test
> 1          /Users/zachriggle/zshz-add-test/a
> 1          /Users/zachriggle/zshz-add-test/b
> 2          /Users/zachriggle/zshz-add-test

I'm a little baffled that you get such small numbers when using `z -l`; that's what I'd expect to see with `z -lr`.

Here's what it looks like on my end right now -- isn't this what you're looking for?

[![asciicast](https://asciinema.org/a/9y7B4epxylcPwKWISPb2G1qdy.svg)](https://asciinema.org/a/9y7B4epxylcPwKWISPb2G1qdy)

**Comment by agkozak** [comment]
Normally, when you do `z -l`, you should see very big numbers to the left. They don't represent the rank field in the database, but rather a relationship between the rank field and the age field. A brand-new addition will be in the tens of thousands at first.

**Comment by agkozak** [comment]
@zachriggle Is this working for you now?

**Comment by zachriggle** [comment]
Things seem to be working better now, thanks!
