### ISSUE TITLE
Request: Please sign up for Github Sponsors

### ISSUE THREAD

**Issue by zachriggle** [agkozak/zsh-z#58]
Hey @agkozak!  It would be great if I could throw some beer money your way, in thanks for the project and fielding my enhancement requests.

I'm not sure what the process is, but there should be info at: https://github.com/sponsors

Notably, please include a $1/mo tier and a $5/mo tier, in addition to whatever else you want.

**Comment by agkozak** [comment]
I did just that! What a great idea.

Let me know if it looks right to you.

**Comment by zachriggle** [comment]
$25 + $5/mo headed your way.

No need for a sponsor badge, but thanks for everything!

**Comment by agkozak** [comment]
Thanks so much - you’re fantastic!
