### ISSUE TITLE
Show tilde instead of HOME during tab completions?

### ISSUE THREAD

**Issue by silesky** [agkozak/zsh-z#60]
Thanks for your work on this project.

Question / feature / bug?:

While `ZSHZ_TILDE=1`

I does not see a tilde when I do `z tab`:
```
 ➤ z /Users/me/bar
/Users/me/bar                                         /Users/me/baz              
/Users/me/barfoo                                    /Users/me/barbaz
/Users/me/barbar                                     /Users/me/bazfoo              
...
```

When I do `z enter`, I see a tilde *instead of* `/Users/me`.
``` 
➤ z 
173335     ~/foo
208498     ~/barfoo
323073     ~/bazfoo
```

Is there a reason that tilde is not visible during tab completions?

**Comment by agkozak** [comment]
I've got a fix for that behavior on the `tilde` branch. Would you be willing to help me test it out?

**Comment by silesky** [comment]
> I've got a fix for that behavior on the `tilde` branch. Would you be willing to help me test it out?

Absolutely!

**Comment by agkozak** [comment]
OK, the fix seems to work, so I've merged it to `master` and am closing this issue. Thanks for helping to make ZSH-z better!
