### ISSUE TITLE
Files and directories both display in autocompletions

### ISSUE THREAD

**Issue by Pound-Hash** [agkozak/zsh-z#62]
The `cd` command completes with:
![20220316_14h18m18s_grim](https://user-images.githubusercontent.com/51193876/158692853-5f704dab-c2c7-4518-97ff-fa55894c683f.png)

`zsh-z` completes with:
![20220316_14h20m10s_grim](https://user-images.githubusercontent.com/51193876/158692963-e9984d21-e0da-4ee6-ba1b-4a0b7a2e9f29.png)

`cd` doesn't suggest files, but `zsh-z` does.

**Comment by agkozak** [comment]
I suspect that there is something in your `.zshrc` that is causing that to happen. Could you post it here? Thanks.

**Comment by agkozak** [comment]
Even more likely is the possibility that you've installed [`zsh-z.plugin.zsh`](https://github.com/agkozak/zsh-z/blob/master/zsh-z.plugin.zsh) somewhere without putting [`_zshz`](https://github.com/agkozak/zsh-z/blob/master/_zshz) in the same directory. That would have the effect you describe. You need `_zshz`; it contains the completions.

**Comment by Pound-Hash** [comment]
> Even more likely is the possibility that you've installed [`zsh-z.plugin.zsh`](https://github.com/agkozak/zsh-z/blob/master/zsh-z.plugin.zsh) somewhere without putting [`_zshz`](https://github.com/agkozak/zsh-z/blob/master/_zshz) in the same directory. That would have the effect you describe. You need `_zshz`; it contains the completions.

This was the fix. Thanks.

The installation of `_zshz` isn't mentioned in the README.

**Comment by agkozak** [comment]
> The installation of _zshz isn't mentioned in the README.

You’re quite right! I’ll fix that later. Thanks for helping to make the plugin better.
