### ISSUE TITLE
Fzf Integration

### ISSUE THREAD

**Issue by crispincornett** [agkozak/zsh-z#66]
I am trying to integrate this plugin with fzf by follow the example found here:

[https://github.com/junegunn/fzf/wiki/examples#z](https://github.com/junegunn/fzf/wiki/examples#z)

However, I am getting the following error:

`z:2: command not found: _z`

Any suggestions?

**Comment by crispincornett** [comment]
Whoops, looks like I just needed to replace the call to `_z` to `zshz`

Sorry about that!

**Comment by FFdhorkin** [comment]
> Whoops, looks like I just needed to replace the call to `_z` to `zshz`
> 
> Sorry about that!

For anyone who finds this in the future, I believe the correct way to do this is add 
`FZ_HISTORY_CD_CMD=zshz`
to your .zshrc
