### ISSUE TITLE
Machine arm64 not supported by this plugin

### ISSUE THREAD

**Issue by nicolastakashi** [agkozak/zsh-z#74]
I'm trying to use this plugin on a Macbook Pro M1 but unfortunately, it's not working, I installed it using zsh plugin and I'm getting the following issue:

```bash
 [zsh-z-plugin] #############################################
 [zsh-z-plugin] Installing z...
 [zsh-z-plugin] -> creating z home dir : /Users/ntakashi/._z/
 [zsh-z-plugin] -> retrieve last version of z...
 [zsh-z-plugin] Machine arm64 not supported by this plugin
 [zsh-z-plugin] Install KO
 [zsh-z-plugin] #############################################
```

Is there any way to support ARM processors?

**Comment by agkozak** [comment]
I’m not familiar with that installer at all. When something says “Installing z….” I’m not even convinced that my Zsh-z plugin is being referred to; it could be the original [rupa/z](https://github.com/rupa/z).

Could you let me know what command you’re using to get the installation started? That might help me to identify what is going on.

You might also want to simply clone `https://github.com/agkozak/zshz` and

    source /path/to/zsh-z.plugin.zsh

just to confirm that the script works for you. Zsh-z has no binary element whatsoever; it should work on any computer that runs Zsh, even 12-year-old versions of Zsh….

**Comment by agkozak** [comment]
Did you get it working?
