### ISSUE TITLE
Completion doesn't work

### ISSUE THREAD

**Issue by student-sx** [agkozak/zsh-z#80]
For me completion with `z` doesn't seem to work. To make sure that the error is not in my `~.zshrc` I started `zsh` via `zsh -f` then I did `source ~/bin/zsh-z.plugin.zsh` and `autoload -U compinit && compinit`. However pressing `z foo` and then `TAB` doesn't complete a path containing `foo` (making sure by executing `z` that there are actually pathes containing `foo` in the list). What did I do wrong?

**Comment by student-sx** [comment]
I thought using zsh in fast doesn't load the `.zshrc`. Nevertheless if I strip down the `.zshrc` to the following and using `zsh` (not `zsh -f`) directly, it doesn't work too:

```
source ~/bin/zsh-z.plugin.zsh

autoload -U compinit
compinit

zstyle ':completion:*' menu select
```

**Comment by agkozak** [comment]
Do you have a `_zshz` file in the same directory as `zsh-z.plugin.zsh`? That's vitally important.

**Comment by student-sx** [comment]
No, I don't.

**Comment by agkozak** [comment]
> No, I don't.

OK, that's the entire problem. Download that and put it in the same directory as `zsh-z.plugin.zsh` and everything should work.

I see that I omitted to mention the importance of having that file in my [instructions](https://github.com/agkozak/zsh-z#general-observations). I'll update those immediately. Thanks for helping me to improve Zsh-z!

**Comment by student-sx** [comment]
Now it works. Thanks!
