### ISSUE TITLE
`ZSHZ[CHOWN,RM,MV]` aren't set when user loads zsh/files early

### ISSUE THREAD

**Issue by z0rc** [agkozak/zsh-z#83]
In my rc files I load zsh/files early to use for other things I do in rc files. Initialization is done via `zmodload -F -m zsh/files b:zf_\*`. zsh-z plugin is sourced afterwards.

This situation breaks conditional logic at https://github.com/agkozak/zsh-z/blob/57803136ed35e14217c21e3dd501750aa448871f/zsh-z.plugin.zsh#L108-L121 resulting in keys `ZSHZ[CHOWN]`, `ZSHZ[RM]` and `ZSHZ[MV]` being unset, which breaks a lot of things in plugin. Each check of `! ${builtins[zf_...]} == 'defined'` is `false`, which skips assignment of keys to `ZSHZ`

**Comment by agkozak** [comment]
Thanks for reporting this problem. I'll look into it later today.

**Comment by agkozak** [comment]
OK, I just pushed changes to the `master` branch that should fix your problem. Thanks for reporting it.
