### ISSUE TITLE
How to load zsh-z into Prezto?

### ISSUE THREAD

**Issue by mrteera** [agkozak/zsh-z#9]
How to load zsh-z into Prezto? It would be insert into this file `.zpreztorc`. But I don't know the plugin name in Prezto.

**Comment by agkozak** [comment]
Clone my repository to your `~/.zprezto/modules` directory, e.g.

    git clone https://github.com/agkozak/zsh-z.git "${ZDOTDIR:-$HOME}/.zprezto/modules"

Then, at the top of your `~/.zpreztorc` file, there should be a section that looks like this:

    zstyle ':prezto:load' pmodule \
        'environment' \
        'terminal' \
        'editor' \
        'history' \
        'directory' \
        'spectrum' \
        'utility' \
        'completion' \
        'prompt'

You'll want to add `'zsh-z'` to the end of that list. Make sure the previous line ends in a backslash:

    zstyle ':prezto:load' pmodule \
        'environment' \
        'terminal' \
        'editor' \
        'history' \
        'directory' \
        'spectrum' \
        'utility' \
        'completion' \
        'prompt' \
        'zsh-z'

Thanks for asking this question. I'll add a small section to the `README.md` about `prezto`.

**Comment by agkozak** [comment]
I've done a little research and written up [instructions](https://github.com/agkozak/zsh-z#for-prezto-users) for how to install `zsh-z` on `prezto`.
